M48
; DRILL file KiCad 10.0.5 date 2026-10-02T12:01:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-02T12:01:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.750
%
G90
G05
T1
X72.1Y117.694
X77.9Y117.694
T2
X4.0Y120.0
X4.0Y4.0
X96.0Y120.0
X96.0Y4.0
T3
X21.0Y95.73
X21.0Y72.73
X79.0Y95.73
X79.0Y72.73
M30
